"""Bidoof's Wish movesets: special-episode main character, guests, fixed-room boss."""

from __future__ import annotations

import contextlib
import io
import struct
from pathlib import Path
from typing import Any

from ndspy.rom import NintendoDSRom
from skytemple_files.common.types.file_types import FileType
from skytemple_files.common.util import (
    get_binary_from_rom,
    get_files_from_rom_with_extension,
    get_ppmdu_config_for_rom,
    set_binary_in_rom,
)
from skytemple_files.data.data_cd.handler import DataCDHandler
from skytemple_files.hardcoded.default_starters import HardcodedDefaultStarters
from skytemple_files.hardcoded.guest_pokemon import GuestPokemonList

from .apply_asm import apply_asm_single, verify_asm_module
from .overlay_caves import get_rom_binary
from .state import AppliedModule, BuildState

GENDER_ID_OFFSET = 600
BOSS_TABLE_ASM = Path("asm") / "generated" / "boss_moves.asm"


def _moves4(value: Any, what: str) -> list[int]:
    moves = [int(m) for m in value]
    if len(moves) != 4:
        raise ValueError(f"{what}: need 4 move ids, got {moves}")
    return moves


def _pc_moves(pc) -> list[int]:
    return [pc.move1, pc.move2, pc.move3, pc.move4]


def _check_entry(what: str, poke_id: int, cur: list[int], ent: dict[str, Any]) -> list[int]:
    if poke_id != int(ent["poke_id"]):
        raise RuntimeError(f"{what}: poke_id {poke_id}, expected {ent['poke_id']}")
    old = _moves4(ent["old_moves"], what)
    new = _moves4(ent["moves"], what)
    if cur not in (old, new):
        raise RuntimeError(f"{what}: moves {cur}, expected {old} or {new}")
    return new


def _patch_arm9(rom: NintendoDSRom, config, manifest: dict[str, Any]) -> list[dict[str, Any]]:
    arm9 = bytearray(get_binary_from_rom(rom, config.bin_sections.arm9))
    before = bytes(arm9)
    edits: list[dict[str, Any]] = []

    pcs = HardcodedDefaultStarters.get_special_episode_pcs(bytes(arm9), config)
    for ent in manifest.get("special_episode_pcs") or []:
        pc = pcs[int(ent["index"])]
        what = f"special episode pc {ent['index']} ({ent.get('name', '')})"
        cur = _pc_moves(pc)
        new = _check_entry(what, pc.poke_id, cur, ent)
        pc.move1, pc.move2, pc.move3, pc.move4 = new
        edits.append({"table": "special_episode_pcs", "index": int(ent["index"]), "was": cur, "moves": new})
    HardcodedDefaultStarters.set_special_episode_pcs(pcs, arm9, config)

    guests = GuestPokemonList.read(bytes(arm9), config)
    for ent in manifest.get("guests") or []:
        g = guests[int(ent["index"])]
        what = f"guest {ent['index']} ({ent.get('name', '')})"
        cur = [int(m) for m in g.moves]
        new = _check_entry(what, g.poke_id, cur, ent)
        g.moves = list(new)
        edits.append({"table": "guests", "index": int(ent["index"]), "was": cur, "moves": new})
    GuestPokemonList.write(guests, arm9, config)

    changed = sum(1 for a, b in zip(before, arm9) if a != b)
    if len(arm9) != len(before) or changed > 8 * len(edits):
        raise RuntimeError(f"arm9 rewrite touched {changed} bytes (len {len(before)} -> {len(arm9)})")
    set_binary_in_rom(rom, config.bin_sections.arm9, bytes(arm9))
    return edits


def _boss_entries(manifest: dict[str, Any]) -> list[tuple[int, int, list[int]]]:
    rows: list[tuple[int, int, list[int]]] = []
    for ent in manifest.get("boss_movesets") or []:
        species = int(ent["species"]) % GENDER_ID_OFFSET
        moves = _moves4(ent["moves"], f"boss {ent.get('name', species)}")
        if species == 0:
            raise ValueError("boss species 0 would end the table")
        for room in ent["fixed_rooms"]:
            if not 0 < int(room) < 256:
                raise ValueError(f"boss {ent.get('name')}: fixed room {room} out of range")
            rows.append((species, int(room), moves))
    return rows


def _boss_table_bytes(rows: list[tuple[int, int, list[int]]]) -> bytes:
    out = bytearray()
    for species, room, moves in rows:
        out += species.to_bytes(2, "little") + bytes([room, 0])
        for m in moves:
            out += m.to_bytes(2, "little")
    return bytes(out) + bytes(2)


def _render_boss_table(module_id: str, rows: list[tuple[int, int, list[int]]]) -> str:
    lines = [
        f"; Auto-generated by true_patches for {module_id} from manifest boss_movesets.",
        "; species (gender id folded), fixed room, pad, 4 move ids. Ends at species 0.",
        ".align 4",
        "BalanceChange_BossMoves:",
    ]
    for species, room, moves in rows:
        lines.append(f"\t.halfword {species}")
        lines.append(f"\t.byte {room}, 0")
        lines.append("\t.halfword " + ", ".join(str(m) for m in moves))
    lines.append("\t.halfword 0")
    lines.append(".align 4")
    return "\n".join(lines) + "\n"


PROCESS_PATHS = ("BALANCE/process.bin", "UTILITY/process.bin")
PROCESS_EFFECT_BASE = 0x022E7240
PROCESS_KIT_POOL = 0xD4


def _kit_entries(code: bytes, kit: int) -> list[tuple[int, int]]:
    ptr = struct.unpack_from("<I", code, PROCESS_KIT_POOL + kit * 4)[0]
    off = ptr - PROCESS_EFFECT_BASE
    if off < 0 or off + 4 > len(code):
        raise RuntimeError(f"process kit {kit} pointer {ptr:#x} is outside the effect")
    rows: list[tuple[int, int]] = []
    p = off
    while p + 4 <= len(code):
        item, count = struct.unpack_from("<HH", code, p)
        if item == 0xFFFF:
            return rows
        rows.append((int(item), int(count)))
        p += 4
    raise RuntimeError(f"process kit {kit} has no terminator")


def _patch_guild_register_items(rom: NintendoDSRom, manifest: dict[str, Any]) -> list[dict[str, Any]]:
    cfg = manifest.get("guild_register_items") or {}
    adds = [(int(e["id"]), int(e.get("count", 1))) for e in (cfg.get("add") or [])]
    if not adds:
        return []
    special = int(cfg.get("special", 71))
    kit = int(cfg.get("kit", 8))
    details: list[dict[str, Any]] = []
    for path in PROCESS_PATHS:
        if path not in rom.filenames:
            continue
        cd = DataCDHandler.deserialize(rom.getFileByName(path))
        effect_id = int(cd.items_effects[special])
        code = bytearray(cd.get_effect_code(effect_id))
        have = {item for item, _cnt in _kit_entries(bytes(code), kit)}
        extra = [(item, count) for item, count in adds if item not in have]
        if extra:
            ptr = struct.unpack_from("<I", code, PROCESS_KIT_POOL + kit * 4)[0]
            off = ptr - PROCESS_EFFECT_BASE
            end = off + 4 * len(_kit_entries(bytes(code), kit))
            if struct.unpack_from("<H", code, end)[0] != 0xFFFF:
                raise RuntimeError(f"{path}: kit {kit} terminator missing")
            blob = b"".join(struct.pack("<HH", item, count) for item, count in extra)
            code[end:end] = blob
            cd.set_effect_code(effect_id, bytes(code))
            rom.setFileByName(path, DataCDHandler.serialize(cd))
        details.append({"path": path, "added": extra, "already": [i for i, _c in adds if i in have]})
    return details


STATUE_ENTID = 554
DEFAULT_SAVE_ONLY_TEMPLATE = "SCRIPT/D10P21A/enter02.ssb"
# Destination bases / challenge hubs: shop or dungeon-guide menus stay vanilla.
# Story dungeon Enter maps (Foggy Forest, etc.) stay vanilla.
# Only same-group mid rests (D10P21A and other P21+ rest maps) become save-only.
HUB_STATUE_MARKERS = (
    b"Visit Shop",
    b"Return to Treasure Town",
    b"You want to purchase",
    b"Equip Items",
    b"You want to redeem",
)


def _is_hub_statue_script(data: bytes) -> bool:
    return any(marker in data for marker in HUB_STATUE_MARKERS)


def _statue_folder(path: str) -> str:
    parts = path.split("/")
    return parts[1] if len(parts) > 1 else path


def _is_story_dungeon_enter(path: str) -> bool:
    """P11* is the first ground map of a dungeon, i.e. story dungeon Enter."""
    folder = _statue_folder(path)
    return folder.endswith(("P11A", "P11B", "P11C"))


def _should_skip_statue(path: str, data: bytes) -> bool:
    return _is_hub_statue_script(data) or _is_story_dungeon_enter(path)


def _dungeon_rest_statue_scripts(rom: NintendoDSRom) -> list[str]:
    """Talk scripts on SCRIPT/D* enter.sse Porygon2 statues (entid 554)."""
    paths: list[str] = []
    names = [
        n
        for n in get_files_from_rom_with_extension(rom, "sse")
        if n.startswith("SCRIPT/D") and n.endswith("/enter.sse")
    ]
    for name in names:
        with contextlib.redirect_stdout(io.StringIO()):
            scene = FileType.SSA.deserialize(rom.getFileByName(name))
        folder = name.rsplit("/", 1)[0]
        for layer in scene.layer_list:
            for act in layer.actors:
                if getattr(act.actor, "entid", None) != STATUE_ENTID:
                    continue
                sid = int(act.script_id)
                if sid < 0:
                    continue
                ssb = f"{folder}/enter{sid:02d}.ssb"
                if ssb in rom.filenames:
                    paths.append(ssb)
    return sorted(set(paths))


def _patch_rest_statue_save_only(rom: NintendoDSRom, manifest: dict[str, Any]) -> dict[str, Any]:
    cfg = manifest.get("rest_statue_save_only") or {}
    template_path = str(cfg.get("template") or DEFAULT_SAVE_ONLY_TEMPLATE)
    template = rom.getFileByName(template_path)
    if len(template) != 72:
        raise RuntimeError(f"{template_path}: expected the 72-byte save-only statue script")
    replaced: list[str] = []
    already: list[str] = []
    skipped: list[str] = []
    for path in _dungeon_rest_statue_scripts(rom):
        cur = rom.getFileByName(path)
        if _should_skip_statue(path, cur):
            skipped.append(path)
            continue
        if cur == template:
            already.append(path)
            continue
        rom.setFileByName(path, template)
        replaced.append(path)
    return {
        "template": template_path,
        "replaced": replaced,
        "already": already,
        "skipped": skipped,
    }


_STORAGE_DENY_NEEDLE = b"Storage isn't available"
# BranchPerformance(58)+BranchPerformance(59) with the same deny target, then
# message_Close (0x96) / message_Menu storage (0x9d 0x00 0x0d 0x00).
_STORAGE_BP_PREFIX = bytes.fromhex("2d003a000100")
_STORAGE_BP59_PREFIX = bytes.fromhex("2d003b000100")


def _iter_ssb_names(rom: NintendoDSRom) -> list[str]:
    names: list[str] = []

    def walk(folder, prefix: str = "") -> None:
        for fname in folder.files:
            names.append(f"{prefix}{fname}" if prefix else fname)
        for sub, child in folder.folders:
            walk(child, f"{prefix}{sub}/")

    walk(rom.filenames)
    return [n for n in names if n.endswith(".ssb")]


def _patch_special_episode_storage_ok(rom: NintendoDSRom) -> dict[str, Any]:
    """Allow Special Episode storage on Expert/Hardcore (all difficulties)."""
    patched: list[str] = []
    already: list[str] = []
    for path in _iter_ssb_names(rom):
        data = bytearray(rom.getFileByName(path))
        if _STORAGE_DENY_NEEDLE not in data:
            continue
        hits = 0
        i = 0
        while True:
            j = data.find(_STORAGE_BP_PREFIX, i)
            if j < 0:
                break
            if (
                j + 16 <= len(data)
                and data[j + 8 : j + 14] == _STORAGE_BP59_PREFIX
                and data[j + 6 : j + 8] == data[j + 14 : j + 16]
                and data[j + 16 : j + 20] == bytes.fromhex("96009d00")
            ):
                # Point both branches at the fallthrough (message_Close).
                # file_off_after_pair - code_base == old_target is not required;
                # retarget to the next opcode's script offset = current + 8+8.
                # Script offsets in these ops are absolute within the SSB code
                # stream; fallthrough is 16 bytes after the first BP start in
                # file terms when the two BPs are contiguous — use tgt+8*2/…
                # Safer: change performance indices 58/59 to 0 (never set).
                data[j + 2] = 0
                data[j + 3] = 0
                data[j + 10] = 0
                data[j + 11] = 0
                hits += 1
                i = j + 16
            else:
                i = j + 1
        if hits:
            rom.setFileByName(path, bytes(data))
            patched.append(path)
        else:
            # Deny text present but already neutralized, or different layout.
            already.append(path)
    return {"patched": patched, "already_or_skipped": already}


def apply_balance_change_module(
    *,
    module_id: str,
    module_dir: Path,
    manifest: dict[str, Any],
    profile: dict[str, Any],
    rom: NintendoDSRom,
    config,
    armips_exe: Path,
    prior_hook_sites: set[int],
    state: BuildState | None,
) -> AppliedModule:
    arm9_edits = _patch_arm9(rom, config, manifest)

    rows = _boss_entries(manifest)
    table_path = module_dir / BOSS_TABLE_ASM
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(_render_boss_table(module_id, rows), encoding="utf-8")

    record, _ = apply_asm_single(
        module_id=module_id,
        module_dir=module_dir,
        manifest=manifest,
        profile=profile,
        rom=rom,
        config=config,
        armips_exe=armips_exe,
        prior_hook_sites=prior_hook_sites,
        state=state,
    )
    guild_items = _patch_guild_register_items(rom, manifest)
    rest_statues = _patch_rest_statue_save_only(rom, manifest)
    storage_ok = (
        _patch_special_episode_storage_ok(rom)
        if manifest.get("special_episode_storage_ok")
        else {}
    )
    from true_patches.balance_change.patch_m_level_exp import (
        patch_m_level_exp_to_pikachu,
    )
    from true_patches.balance_change.patch_se_entry_split import (
        patch_se_entry_split_and_levels,
    )

    m_level_exp = patch_m_level_exp_to_pikachu(rom)
    se_split = patch_se_entry_split_and_levels(rom, state=state, record=record)
    record.data.append(
        {
            "arm9_edits": arm9_edits,
            "boss_movesets": [
                {"species": s, "fixed_room": r, "moves": m} for s, r, m in rows
            ],
            "guild_register_items": guild_items,
            "rest_statue_save_only": rest_statues,
            "special_episode_storage_ok": storage_ok,
            **m_level_exp,
            **se_split,
        }
    )
    return record


def verify_balance_change_module(
    rom_path: Path,
    manifest: dict[str, Any],
    profile: dict[str, Any],
    state_mod: AppliedModule | None,
) -> None:
    verify_asm_module(rom_path, manifest, profile, state_mod)

    rom = NintendoDSRom(rom_path.read_bytes())
    config = get_ppmdu_config_for_rom(rom)
    arm9 = get_binary_from_rom(rom, config.bin_sections.arm9)
    pcs = HardcodedDefaultStarters.get_special_episode_pcs(arm9, config)
    for ent in manifest.get("special_episode_pcs") or []:
        pc = pcs[int(ent["index"])]
        if pc.poke_id != int(ent["poke_id"]) or _pc_moves(pc) != _moves4(ent["moves"], "pc"):
            raise AssertionError(f"special episode pc {ent['index']}: {pc.poke_id} {_pc_moves(pc)}")
    guests = GuestPokemonList.read(arm9, config)
    for ent in manifest.get("guests") or []:
        g = guests[int(ent["index"])]
        if g.poke_id != int(ent["poke_id"]) or list(g.moves) != _moves4(ent["moves"], "guest"):
            raise AssertionError(f"guest {ent['index']}: {g.poke_id} {list(g.moves)}")

    if state_mod is None or not state_mod.caves:
        raise AssertionError("balance_change: no cave in state")
    from true_patches.balance_change.patch_se_entry_split import verify_se_table_storage
    verify_se_table_storage(rom, state_mod)
    cave = state_mod.caves[0]
    ov36 = get_rom_binary(rom, cave.overlay)
    table = _boss_table_bytes(_boss_entries(manifest))
    if ov36.find(table, cave.file_offset, cave.file_offset + cave.size) < 0:
        raise AssertionError("balance_change: boss moveset table missing from cave")

    cfg = manifest.get("guild_register_items") or {}
    want = {int(e["id"]) for e in (cfg.get("add") or [])}
    if want:
        special = int(cfg.get("special", 71))
        kit = int(cfg.get("kit", 8))
        cd = DataCDHandler.deserialize(rom.getFileByName("BALANCE/process.bin"))
        code = bytes(cd.get_effect_code(int(cd.items_effects[special])))
        have = {item for item, _cnt in _kit_entries(code, kit)}
        missing = want - have
        if missing:
            raise AssertionError(f"balance_change: guild kit missing {sorted(missing)}")

    cfg = manifest.get("rest_statue_save_only") or {}
    template_path = str(cfg.get("template") or DEFAULT_SAVE_ONLY_TEMPLATE)
    template = rom.getFileByName(template_path)
    leftover = []
    overwritten_skip = []
    for path in _dungeon_rest_statue_scripts(rom):
        data = rom.getFileByName(path)
        if _is_story_dungeon_enter(path) or _is_hub_statue_script(data):
            if data == template:
                overwritten_skip.append(path)
            continue
        if data != template:
            leftover.append(path)
    if leftover:
        raise AssertionError(f"balance_change: mid-group rest statues still not save-only: {leftover}")
    if overwritten_skip:
        raise AssertionError(
            f"balance_change: enter/hub statues were made save-only: {overwritten_skip}"
        )

    if manifest.get("special_episode_storage_ok"):
        left = []
        for path in _iter_ssb_names(rom):
            data = rom.getFileByName(path)
            if _STORAGE_DENY_NEEDLE not in data:
                continue
            i = 0
            while True:
                j = data.find(_STORAGE_BP_PREFIX, i)
                if j < 0:
                    break
                if (
                    j + 16 <= len(data)
                    and data[j + 8 : j + 14] == _STORAGE_BP59_PREFIX
                    and data[j + 6 : j + 8] == data[j + 14 : j + 16]
                    and data[j + 16 : j + 20] == bytes.fromhex("96009d00")
                ):
                    # Still has live Expert/Hardcore indices.
                    if data[j + 2] == 0x3A and data[j + 10] == 0x3B:
                        left.append(path)
                    break
                i = j + 1
        if left:
            raise AssertionError(f"balance_change: storage still gated on Expert+: {left}")

    from true_patches.balance_change.patch_m_level_exp import (
        M_LEVEL_PATHS,
        PIKACHU_INDEX,
        _load_entry,
    )

    for path in M_LEVEL_PATHS:
        pack = FileType.BIN_PACK.deserialize(rom.getFileByName(path))
        pika = _load_entry(pack, PIKACHU_INDEX)
        pika_exp = [int(pika[i].experience_required) for i in range(100)]
        for index in (0, 9, 25, len(pack) - 1):
            entry = _load_entry(pack, index)
            got = [int(entry[i].experience_required) for i in range(100)]
            if got != pika_exp:
                raise AssertionError(
                    f"balance_change: {path} entry {index} EXP curve != Pikachu"
                )

    from collections import defaultdict

    from true_patches.balance_change.patch_se_entry_split import (
        SPLIT_GROUPS,
        VANILLA_RESTORE_ENTRIES,
    )
    from skytemple_files.hardcoded.fixed_floor import (
        HardcodedFixedFloorTables,
        MonsterSpawnType,
    )

    ov29 = get_binary_from_rom(rom, config.bin_sections.overlay29)
    monsters = HardcodedFixedFloorTables.get_monster_spawn_list(ov29, config)
    target_mds = set().union(*SPLIT_GROUPS)
    for group in SPLIT_GROUPS:
        entry_to_mds: dict[int, set[int]] = defaultdict(set)
        for sp in monsters:
            if sp.enemy_settings != MonsterSpawnType.ENEMY_STRONG:
                continue
            md = int(sp.md_idx)
            if md not in group:
                continue
            entry_to_mds[int(sp.stats_entry)].add(md)
        shared = {e: sorted(mds) for e, mds in entry_to_mds.items() if len(mds) > 1}
        if shared:
            raise AssertionError(
                f"balance_change: SE group {sorted(group)} still shares entries: "
                f"{shared}"
            )
    parked = [
        (int(sp.md_idx), int(sp.stats_entry))
        for sp in monsters
        if sp.enemy_settings == MonsterSpawnType.ENEMY_STRONG
        and int(sp.md_idx) in target_mds
        and int(sp.stats_entry) in VANILLA_RESTORE_ENTRIES
    ]
    if parked:
        raise AssertionError(
            f"balance_change: split SE still on reserved entries 35/55: {parked}"
        )
    try:
        mirror = rom.getFileByName("BALANCE/fr_mst.bin")
    except Exception as exc:
        raise AssertionError(f"balance_change: BALANCE/fr_mst.bin missing: {exc}") from exc
    if len(mirror) < 99 * 12 or len(mirror) % 12 != 0:
        raise AssertionError(
            f"balance_change: fr_mst.bin bad size {len(mirror)}"
        )
    for entry, vanilla in VANILLA_RESTORE_ENTRIES.items():
        got = mirror[entry * 12 : (entry + 1) * 12]
        if got != vanilla:
            raise AssertionError(
                f"balance_change: entry {entry} not restored to vanilla "
                f"(got {got.hex()}, want {vanilla.hex()})"
            )
