from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path


def write_generated_inc_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def write_generated_inc(
    path: Path,
    *,
    room_charge_code_file_off: int,
    module_id: str,
) -> None:
    write_generated_inc_text(
        path,
        f"; Auto-generated by true_patches for {module_id}\n"
        f".definelabel RoomChargeCodeFileOff, 0x{room_charge_code_file_off:X}\n",
    )


def _install_generated_inc(work: Path, generated_inc: Path | None) -> None:
    if generated_inc is None:
        return
    shutil.copy2(generated_inc, work / "generated.inc")
    common = work / "common"
    if common.is_dir():
        shutil.copy2(generated_inc, common / "generated.inc")


def run_armips_module(
    *,
    armips: Path,
    asm_dir: Path,
    asm_entry: str,
    overlay_path: Path,
    overlay_filename: str,
    generated_inc: Path | None = None,
) -> None:
    with tempfile.TemporaryDirectory(prefix="true_patches_") as tmp:
        work = Path(tmp) / "build"
        shutil.copytree(asm_dir, work)

        _install_generated_inc(work, generated_inc)

        shutil.copy2(overlay_path, work / overlay_filename)
        wrapper = "_tp_entry.asm"
        (work / wrapper).write_text(f'.include "{asm_entry}"\n', encoding="utf-8")

        result = subprocess.run(
            [str(armips), wrapper],
            cwd=work,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "armips failed:\n"
                + (result.stdout or "")
                + "\n"
                + (result.stderr or "")
            )

        shutil.copy2(work / overlay_filename, overlay_path)


def run_armips_bundle(
    *,
    armips: Path,
    asm_dir: Path,
    asm_entry: str,
    binaries: dict[str, Path],
    generated_inc: Path | None = None,
) -> None:
    """Run one armips entry that patches multiple ROM binaries (e.g. arm9 + ov29 + ov31)."""
    with tempfile.TemporaryDirectory(prefix="true_patches_bundle_") as tmp:
        work = Path(tmp) / "build"
        shutil.copytree(asm_dir, work)
        _install_generated_inc(work, generated_inc)

        for name, src in binaries.items():
            shutil.copy2(src, work / name)

        wrapper = "_tp_entry.asm"
        (work / wrapper).write_text(f'.include "{asm_entry}"\n', encoding="utf-8")

        result = subprocess.run(
            [str(armips), wrapper],
            cwd=work,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "armips bundle failed:\n"
                + (result.stdout or "")
                + "\n"
                + (result.stderr or "")
            )

        for name, src in binaries.items():
            shutil.copy2(work / name, src)
