from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .cave_gap import cave_inter_gap_bytes
from .state import BuildState


@dataclass(frozen=True)
class FileRange:
    start: int
    end: int

    def overlaps(self, start: int, size: int) -> bool:
        end = start + size
        return start < self.end and end > self.start


def _overlay_keys(name: str) -> set[str]:
    if name in ("ov29", "overlay29", "overlay_0029"):
        return {"ov29", "overlay29", "overlay_0029"}
    if name in ("arm9", "arm9.bin"):
        return {"arm9", "arm9.bin"}
    if name in ("ov31", "overlay31", "overlay_0031"):
        return {"ov31", "overlay31", "overlay_0031"}
    if name in ("ov36", "overlay36", "overlay_0036"):
        return {"ov36", "overlay36", "overlay_0036"}
    return {name}


def reserved_file_ranges(
    state: BuildState | None,
    binary: str,
    *,
    extra: Iterable[FileRange] | None = None,
    exclude_module: str | None = None,
) -> list[FileRange]:
    """File-offset ranges already claimed by prior modules (from build state)."""
    keys = _overlay_keys(binary)
    ranges: list[FileRange] = []
    gap = cave_inter_gap_bytes()
    if state:
        for mod in state.applied:
            if exclude_module and mod.id == exclude_module:
                continue
            for cave in mod.caves:
                if cave.overlay in keys:
                    end = cave.file_offset + cave.size + gap
                    ranges.append(FileRange(cave.file_offset, end))
    if extra:
        ranges.extend(extra)
    return ranges


def format_load_address_inc(
    *,
    module_id: str,
    base_label: str,
    base_load: int,
    slots: list[tuple[str, int]],
) -> str:
    """generated.inc: base RAM label + slot symbols at fixed strides from base."""
    lines = [
        f"; Auto-generated by true_patches for {module_id}",
        f".definelabel {base_label}, 0x{base_load:X}",
    ]
    for name, offset in slots:
        if offset == 0:
            lines.append(f".definelabel {name}, {base_label}")
        else:
            lines.append(f".definelabel {name}, {base_label} + 0x{offset:X}")
    return "\n".join(lines) + "\n"


def format_file_offset_inc(
    *,
    module_id: str,
    label: str,
    file_offset: int,
) -> str:
    lines = [
        f"; Auto-generated by true_patches for {module_id}",
        f".definelabel {label}, 0x{file_offset:X}",
    ]
    return "\n".join(lines) + "\n"


def parse_slot_manifest(cave_cfg: dict) -> list[tuple[str, int]]:
    stride = int(cave_cfg.get("slot_stride", 0x100))
    slots_cfg = cave_cfg.get("slots") or []
    out: list[tuple[str, int]] = []
    for idx, entry in enumerate(slots_cfg):
        if isinstance(entry, str):
            out.append((entry, idx * stride))
        elif isinstance(entry, dict):
            name = entry["name"]
            offset = int(entry.get("offset", idx * stride))
            out.append((name, offset))
        else:
            raise ValueError(f"invalid cave slot entry: {entry!r}")
    return out
