#!/usr/bin/env python3
"""Regenerate strings_menu.yaml for Spinda drink submenu (V0..50 per stat)."""

from __future__ import annotations

from pathlib import Path

STAT_LABELS = ("HP", "Atk", "SpA", "Def", "SpD", "Spe")
DISPLAY_BASE = 19300
MAX_V = 50


def build_entries() -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for stat_index, label in enumerate(STAT_LABELS):
        for v in range(MAX_V + 1):
            string_id = DISPLAY_BASE + stat_index * (MAX_V + 1) + v
            out.append((string_id, f"{label}({v})"))
    reset_id = DISPLAY_BASE + len(STAT_LABELS) * (MAX_V + 1)
    out.append((reset_id, "Reset"))
    return out


def render_yaml(entries: list[tuple[int, str]]) -> str:
    lines = [
        "# Auto-generated by generate_menu_strings.py",
        "# Display string N uses code id N+1 in menu table halfwords.",
        "entries:",
    ]
    for string_id, text in entries:
        lines.append(f"  - id: {string_id}")
        lines.append(f'    text: "{text}"')
    return "\n".join(lines) + "\n"


def main() -> None:
    out_path = Path(__file__).resolve().parent / "strings_menu.yaml"
    entries = build_entries()
    out_path.write_text(render_yaml(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} entries -> {out_path}")
    print(f"  display ids {DISPLAY_BASE}..{entries[-1][0]}")


if __name__ == "__main__":
    main()
