#!/usr/bin/env python3
"""Generate orb charge table asm for true_patches/orb_charges (ov29 + count for generated.inc)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODULE = Path(__file__).resolve().parent
OUT_OV29 = MODULE / "asm" / "generated" / "orb_charge_table_ov29.asm"
OUT_ARM9 = MODULE / "asm" / "generated" / "orb_charge_table_arm9.asm"

CHARGES_BY_ROM_NAME: dict[str, int] = {
    "Escape Orb": 1,
    "Luminous Orb": 1,
    "Mobile Orb": 1,
    "Stairs Orb": 1,
    "Invisify Orb": 1,
    "Health Orb": 1,
    "Petrify Orb": 1,
    "Slumber Orb": 1,
    "Totter Orb": 1,
    "Shocker Orb": 3,
    "Sizebust Orb": 1,
    "Lure Orb": 3,
    "One-Room Orb": 1,
    "Trawl Orb": 1,
    "Cleanse Orb": 1,
    "Two-Edge Orb": 3,
    "Premier Gift": 1,
    "Radar Orb": 3,
    "Scanner Orb": 3,
    "See-Trap Orb": 3,
    "Trapbust Orb": 3,
    "Warp Orb": 3,
    "Switcher Orb": 3,
    "Blowback Orb": 3,
    "Hurl Orb": 3,
    "Rebound Orb": 1,
    "Stayaway Orb": 3,
    "Quick Orb": 3,
    "Evasion Orb": 3,
    "Longtoss Orb": 3,
    "Pierce Orb": 3,
    "Drought Orb": 1,
    "Decoy Orb": 3,
    "Mug Orb": 1,
    "One-Shot Orb": 3,
    "Pounce Orb": 3,
    "Identify Orb": 1,
    "Snatch Orb": 1,
    "Hail Orb": 3,
    "Sunny Orb": 3,
    "Rainy Orb": 3,
    "Sandy Orb": 3,
    "Transfer Orb": 3,
    "Aim Orb": 3,
    "Grudge Orb": 1,
    "Rollcall Orb": 3,
    "Cure Orb": 3,
    "Lob Orb": 3,
    "Rocky Orb": 3,
    "Safe Orb": 3,
    "Silence Orb": 1,
    "Gravity Orb": 3,
    "Slow Orb": 3,
}


def plain_item_name(raw: str) -> str:
    return re.sub(r"\[.*?\]", "", raw).strip()


def build_table_from_rom(rom_path: Path) -> list[tuple[int, int, str]]:
    from ndspy.rom import NintendoDSRom
    from skytemple_files.common.util import get_ppmdu_config_for_rom
    from skytemple_files.data.item_p.handler import ItemPHandler
    from skytemple_files.data.str.handler import StrHandler

    rom = NintendoDSRom(rom_path.read_bytes())
    item_p = ItemPHandler.deserialize(rom.getFileByName("BALANCE/item_p.bin"))
    config = get_ppmdu_config_for_rom(rom)
    block = config.string_index_data.string_blocks["Item Names"]
    strings = StrHandler.deserialize(
        rom.getFileByName("MESSAGE/text_e.str"), string_encoding=config.string_encoding
    )

    rows: list[tuple[int, int, str]] = []
    missing: list[str] = []
    for name, charges in sorted(CHARGES_BY_ROM_NAME.items(), key=lambda x: x[0]):
        found = False
        for item_id, entry in enumerate(item_p.item_list):
            if entry.category != 9:
                continue
            rom_name = plain_item_name(strings.strings[block.begin + item_id])
            if rom_name == name:
                rows.append((item_id, charges, name))
                found = True
                break
        if not found:
            missing.append(name)

    if missing:
        print("WARNING: not found in ROM (cat 9):", ", ".join(missing))

    rows.sort(key=lambda r: r[0])
    return rows


def emit_asm(rows: list[tuple[int, int, str]], label: str) -> str:
    lines = [
        "; Auto-generated by true_patches/orb_charges/generate_table.py",
        f"; {len(rows)} orb item IDs (charge=3 only; charge=1 uses menu default Use(1))",
        "",
        f"{label}:",
    ]
    for item_id, charges, name in rows:
        lines.append(f"\t.halfword {item_id}  ; {name}")
        lines.append(f"\t.byte {charges}")
        lines.append("\t.byte 0")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    rom_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        ROOT / "PatchTesting" / "Explorers of Alpha" / "Explorers of Alpha.nds"
    )
    if not rom_path.is_file():
        raise SystemExit(f"ROM not found: {rom_path}")

    rows = build_table_from_rom(rom_path)
    rows = [row for row in rows if row[1] == 3]
    OUT_OV29.parent.mkdir(parents=True, exist_ok=True)
    OUT_OV29.write_text(emit_asm(rows, "OrbChargeTableOv29"), encoding="utf-8")
    OUT_ARM9.write_text(emit_asm(rows, "OrbChargeTable"), encoding="utf-8")
    print(f"Wrote {OUT_OV29} ({len(rows)} entries)")
    print(f"Wrote {OUT_ARM9} ({len(rows)} entries)")


if __name__ == "__main__":
    main()
