#!/usr/bin/env python3
"""Generate item_cd stub asm files from berries.yaml (Pattern B)."""

from __future__ import annotations

import sys
from pathlib import Path

MODULE = Path(__file__).resolve().parent
BERRIES_YAML = MODULE / "berries.yaml"
OUT_DIR = MODULE / "asm" / "generated"

STUB_TEMPLATE = """\
; Auto-generated by generate_berry_stubs.py — do not edit.
.relativeinclude on
.nds
.arm

.definelabel MaxSize, 0xCC4
.include "lib/dunlib_us.asm"
.include "common/berry_boost_us.asm"

.create "./code_out.bin", 0x0231BE50
\t.org ItemStartAddress
\t.area MaxSize
\t\tmov r0, r8
\t\tmov r1, r7
\t\tbl {cave_symbol}
\t\tb ItemJumpAddress
\t.endarea
.close
"""


def load_effects() -> list[dict]:
    import yaml

    doc = yaml.safe_load(BERRIES_YAML.read_text(encoding="utf-8"))
    effects = doc.get("effects") or []
    if not effects:
        raise SystemExit(f"No effects in {BERRIES_YAML}")
    return effects


def stub_filename(item_id: int) -> str:
    return f"item_{item_id}_stub.asm"


def emit_stub(cave_symbol: str) -> str:
    return STUB_TEMPLATE.format(cave_symbol=cave_symbol)


def main() -> None:
    effects = load_effects()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for effect in effects:
        item_id = int(effect["item_id"])
        cave_symbol = str(effect["cave_symbol"])
        path = OUT_DIR / stub_filename(item_id)
        path.write_text(emit_stub(cave_symbol), encoding="utf-8")
        written.append(path.name)

    print(f"Wrote {len(written)} item_cd stubs -> {OUT_DIR}")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
