#!/usr/bin/env python3
"""Generate orb_charge_table.asm from ROM item names + user charge spec."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_ARM9 = ROOT / "asm_patches" / "orb_charges" / "generated" / "orb_charge_table_arm9.asm"
OUT_OV29 = ROOT / "asm_patches" / "orb_charges" / "generated" / "orb_charge_table_ov29.asm"

# ROM display name -> max charges. Only names present in the US EoS ROM are included.
CHARGES_BY_ROM_NAME: dict[str, int] = {
    # 1 use
    "Escape Orb": 1,
    "Luminous Orb": 1,
    "Mobile Orb": 1,
    "Stairs Orb": 1,
    "Invisify Orb": 1,
    "Health Orb": 1,
    "Petrify Orb": 1,
    "Slumber Orb": 1,
    "Totter Orb": 1,
    "Shocker Orb": 1,
    "Sizebust Orb": 1,
    "One-Room Orb": 1,
    "Trawl Orb": 1,
    "Cleanse Orb": 1,
    "Two-Edge Orb": 1,
    "Premier Gift": 1,
    # 3 uses
    "Radar Orb": 3,
    "Scanner Orb": 3,
    "See-Trap Orb": 3,
    "Trapbust Orb": 3,
    "Warp Orb": 3,
    "Switcher Orb": 3,
    "Blowback Orb": 3,
    "Hurl Orb": 3,
    "Rebound Orb": 3,
    "Stayaway Orb": 3,
    "Quick Orb": 3,
    "Evasion Orb": 3,
    "Longtoss Orb": 3,
    "Pierce Orb": 3,
    "Drought Orb": 3,
    "Decoy Orb": 3,
    "Mug Orb": 3,
    "One-Shot Orb": 3,
    "Pounce Orb": 3,
    "Identify Orb": 3,
    "Snatch Orb": 3,
    "Hail Orb": 3,
    "Sunny Orb": 3,
    "Rainy Orb": 3,
    "Sandy Orb": 3,
    "Transfer Orb": 3,
    "Aim Orb": 3,
    "Grudge Orb": 3,
    "Rollcall Orb": 3,
    "Cure Orb": 3,
    "Lob Orb": 3,
    "Rocky Orb": 3,
    "Safe Orb": 3,
    "Silence Orb": 3,
    "Gravity Orb": 3,
    "Slow Orb": 3,
}


def plain_item_name(raw: str) -> str:
    return re.sub(r"\[.*?\]", "", raw).strip()


def build_table_from_rom(rom_path: Path) -> list[tuple[int, int, str]]:
    from ndspy.rom import NintendoDSRom
    from skytemple_files.common.util import get_ppmdu_config_for_rom
    from skytemple_files.data.item_p.handler import ItemPHandler
    from skytemple_files.data.str.handler import StrHandler

    rom = NintendoDSRom(rom_path.read_bytes())
    item_p = ItemPHandler.deserialize(rom.getFileByName("BALANCE/item_p.bin"))
    config = get_ppmdu_config_for_rom(rom)
    block = config.string_index_data.string_blocks["Item Names"]
    strings = StrHandler.deserialize(
        rom.getFileByName("MESSAGE/text_e.str"), string_encoding=config.string_encoding
    )

    rows: list[tuple[int, int, str]] = []
    missing: list[str] = []
    for name, charges in sorted(CHARGES_BY_ROM_NAME.items(), key=lambda x: x[0]):
        found = False
        for item_id, entry in enumerate(item_p.item_list):
            if entry.category != 9:
                continue
            rom_name = plain_item_name(strings.strings[block.begin + item_id])
            if rom_name == name:
                rows.append((item_id, charges, name))
                found = True
                break
        if not found:
            missing.append(name)

    if missing:
        print("WARNING: not found in ROM (cat 9):", ", ".join(missing))

    rows.sort(key=lambda r: r[0])
    return rows


def emit_asm(rows: list[tuple[int, int, str]], label: str) -> str:
    lines = [
        "; Auto-generated by tools/generate_orb_charge_table.py",
        f"; {len(rows)} orb item IDs (category 9, charge=3 only; charge=1 stays vanilla)",
        "",
        f"{label}:",
    ]
    for item_id, charges, name in rows:
        lines.append(f"\t.halfword {item_id}  ; {name}")
        lines.append(f"\t.byte {charges}")
        lines.append("\t.byte 0")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    rom = ROOT / (
        "4273 - Pokemon Mystery Dungeon - Explorers of Sky (US)(XenoPhobia)"
        "-patched_orbs_roomcharge_nodarkness_berryboost_orbcharges.nds"
    )
    if not rom.is_file():
        rom = ROOT / (
            "4273 - Pokemon Mystery Dungeon - Explorers of Sky (US)(XenoPhobia)"
            "-patched_orbs_roomcharge_nodarkness_berryboost.nds"
        )
    if not rom.is_file():
        rom = ROOT / "Explorers of Alpha_Non_Save_Successed.nds"
    if not rom.is_file():
        raise SystemExit(f"base ROM not found: {rom}")

    rows = build_table_from_rom(rom)
    # charge=1 orbs behave like vanilla (single use); only patch multi-use (3).
    rows = [row for row in rows if row[1] == 3]
    OUT_ARM9.parent.mkdir(parents=True, exist_ok=True)
    OUT_ARM9.write_text(emit_asm(rows, "OrbChargeTable"), encoding="utf-8")
    OUT_OV29.write_text(emit_asm(rows, "OrbChargeTableOv29"), encoding="utf-8")

    offsets = ROOT / "asm_patches" / "orb_charges" / "common" / "offsetsUS.asm"
    text = offsets.read_text(encoding="utf-8")
    text = re.sub(
        r"OrbChargeTableCount equ \d+",
        f"OrbChargeTableCount equ {len(rows)}",
        text,
    )
    offsets.write_text(text, encoding="utf-8")

    by_charge: dict[int, int] = {}
    for _, c, _ in rows:
        by_charge[c] = by_charge.get(c, 0) + 1
    print(f"Wrote {OUT_ARM9} and {OUT_OV29} ({len(rows)} entries)")
    print("By max charges:", dict(sorted(by_charge.items())))


if __name__ == "__main__":
    main()
