#!/usr/bin/env python3
"""Generate orb pack -> real orb ID-swap tables (all category-9 orbs)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_CONST = ROOT / "asm_patches" / "orb_dummies" / "generated" / "orb_dummy_constants.asm"
OUT_DATA = ROOT / "asm_patches" / "orb_dummies" / "generated" / "orb_dummy_table_data.asm"
OUT_PY = ROOT / "asm_patches" / "orb_dummies" / "generated" / "orb_dummy_map.py"

REAL_ORB_ID_START = 1401

CHARGES_BY_ROM_NAME: dict[str, int] = {
    "Escape Orb": 1,
    "Luminous Orb": 1,
    "Mobile Orb": 1,
    "Stairs Orb": 1,
    "Invisify Orb": 1,
    "Health Orb": 1,
    "Petrify Orb": 1,
    "Slumber Orb": 1,
    "Totter Orb": 1,
    "Sizebust Orb": 1,
    "Shocker Orb": 1,
    "One-Room Orb": 1,
    "Trawl Orb": 1,
    "Radar Orb": 3,
    "Scanner Orb": 3,
    "See-Trap Orb": 3,
    "Trapbust Orb": 3,
    "Warp Orb": 3,
    "Switcher Orb": 3,
    "Blowback Orb": 3,
    "Hurl Orb": 3,
    "Rebound Orb": 3,
    "Stayaway Orb": 3,
    "Quick Orb": 3,
    "Evasion Orb": 3,
    "Longtoss Orb": 3,
    "Pierce Orb": 3,
    "Drought Orb": 3,
    "Decoy Orb": 3,
    "Mug Orb": 3,
    "One-Shot Orb": 3,
    "Pounce Orb": 3,
    "Identify Orb": 3,
    "Snatch Orb": 3,
    "Hail Orb": 5,
    "Sunny Orb": 5,
    "Rainy Orb": 5,
    "Sandy Orb": 5,
    "Cleanse Orb": 5,
}


def plain_item_name(raw: str) -> str:
    return re.sub(r"\[.*?\]", "", raw).strip()


def build_rows(rom_path: Path) -> list[tuple[int, int, int, str]]:
    from ndspy.rom import NintendoDSRom
    from skytemple_files.common.util import get_ppmdu_config_for_rom
    from skytemple_files.data.item_p.handler import ItemPHandler
    from skytemple_files.data.str.handler import StrHandler

    rom = NintendoDSRom(rom_path.read_bytes())
    item_p = ItemPHandler.deserialize(rom.getFileByName("BALANCE/item_p.bin"))
    config = get_ppmdu_config_for_rom(rom)
    block = config.string_index_data.string_blocks["Item Names"]
    strings = StrHandler.deserialize(
        rom.getFileByName("MESSAGE/text_e.str"), string_encoding=config.string_encoding
    )

    rows: list[tuple[int, int, int, str]] = []
    real_id = REAL_ORB_ID_START
    for item_id, entry in enumerate(item_p.item_list):
        if entry.category != 9:
            continue
        name = plain_item_name(strings.strings[block.begin + item_id])
        count = CHARGES_BY_ROM_NAME.get(name, 1)
        rows.append((item_id, real_id, count, name))
        real_id += 1

    rows.sort(key=lambda r: r[0])
    return rows


def emit_constants(rows: list[tuple[int, int, int, str]]) -> str:
    return (
        "; Auto-generated by tools/generate_orb_dummy_table.py\n"
        f"OrbDummyTableCount equ {len(rows)}\n"
        f"REAL_ORB_ID_START equ {REAL_ORB_ID_START}\n"
    )


def emit_table_data(rows: list[tuple[int, int, int, str]]) -> str:
    lines = ["; Auto-generated by tools/generate_orb_dummy_table.py"]
    for pack_id, real_id, count, name in rows:
        lines.append(f"\t.halfword {pack_id}  ; {name} pack")
        lines.append(f"\t.halfword {real_id}")
        lines.append(f"\t.byte {count}")
        lines.append("\t.byte 0")
    lines.append("")
    return "\n".join(lines)


def emit_py(rows: list[tuple[int, int, int, str]]) -> str:
    lines = [
        "# Auto-generated by tools/generate_orb_dummy_table.py",
        f"REAL_ORB_ID_START = {REAL_ORB_ID_START}",
        "ORB_DUMMY_ROWS = [",
    ]
    for pack_id, real_id, count, name in rows:
        lines.append(f"    ({pack_id}, {real_id}, {count}, {name!r}),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    rom = ROOT / (
        "4273 - Pokemon Mystery Dungeon - Explorers of Sky (US)(XenoPhobia)"
        "-patched_orbs_roomcharge_nodarkness_berryboost.nds"
    )
    if not rom.is_file():
        raise SystemExit(f"base ROM not found: {rom}")

    rows = build_rows(rom)
    OUT_CONST.parent.mkdir(parents=True, exist_ok=True)
    OUT_CONST.write_text(emit_constants(rows), encoding="utf-8")
    OUT_DATA.write_text(emit_table_data(rows), encoding="utf-8")
    OUT_PY.write_text(emit_py(rows), encoding="utf-8")

    by_count: dict[int, int] = {}
    for _, _, count, _ in rows:
        by_count[count] = by_count.get(count, 0) + 1
    print(
        f"Wrote {OUT_CONST.name}, {OUT_DATA.name}, {OUT_PY.name} "
        f"({len(rows)} orb packs -> {REAL_ORB_ID_START}..{REAL_ORB_ID_START + len(rows) - 1})"
    )
    print("By pack size:", dict(sorted(by_count.items())))


if __name__ == "__main__":
    main()
