#!/usr/bin/env python3
"""Generate TM charge table asm for true_patches/tm_read (ov29 cave only)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

MODULE = Path(__file__).resolve().parent
OUT_OV29 = MODULE / "asm" / "generated" / "tm_charge_table_ov29.asm"
TM_MAX_CHARGES = 3


def build_rows(rom_path: Path) -> list[tuple[int, int, str]]:
    from ndspy.rom import NintendoDSRom
    from skytemple_files.common.util import get_ppmdu_config_for_rom
    from skytemple_files.data.item_p.handler import ItemPHandler
    from skytemple_files.data.str.handler import StrHandler

    rom = NintendoDSRom(rom_path.read_bytes())
    item_p = ItemPHandler.deserialize(rom.getFileByName("BALANCE/item_p.bin"))
    config = get_ppmdu_config_for_rom(rom)
    block = config.string_index_data.string_blocks["Item Names"]
    strings = StrHandler.deserialize(
        rom.getFileByName("MESSAGE/text_e.str"), string_encoding=config.string_encoding
    )

    def plain(item_id: int) -> str:
        return re.sub(r"\[.*?\]", "", strings.strings[block.begin + item_id]).strip()

    rows: list[tuple[int, int, str]] = []
    for item_id, entry in enumerate(item_p.item_list):
        if entry.category != 5:
            continue
        rows.append((item_id, TM_MAX_CHARGES, plain(item_id)))
    rows.sort(key=lambda r: r[0])
    return rows


def emit_asm(rows: list[tuple[int, int, str]], label: str) -> str:
    lines = [
        "; Auto-generated by true_patches/tm_read/generate_table.py",
        f"; {len(rows)} TM item IDs (category 5), max {TM_MAX_CHARGES} Read charges each",
        "",
        f"{label}:",
    ]
    for item_id, charges, name in rows:
        lines.append(f"\t.halfword {item_id}  ; {name}")
        lines.append(f"\t.byte {charges}")
        lines.append("\t.byte 0")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    rom_path = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if rom_path is None or not rom_path.is_file():
        raise SystemExit(f"ROM not found: {rom_path}")

    rows = build_rows(rom_path)
    OUT_OV29.parent.mkdir(parents=True, exist_ok=True)
    OUT_OV29.write_text(emit_asm(rows, "TmChargeTableOv29"), encoding="utf-8")
    print(f"Wrote {OUT_OV29} ({len(rows)} TMs, max charges={TM_MAX_CHARGES})")


if __name__ == "__main__":
    main()
